### ISSUE TITLE
The requested resource could not be found.

### ISSUE THREAD

**Issue by tikos** [geotrellis/geotrellis-chatta-demo#4]
Hi,

I am quite new here with GeoTrellis and these kind of stuff anyway I need to run it. I had many problems with that downloaded demo here ... dependencies are wrong, some was not yet compiled, assembly not found and everything is "okey" now (I guess). I deleted assembly´s code part from every file, downgrade Java because I had one JAR broken (even when I re-downloaded it, instaled Java again) ... AND finally, I am almost running this demo. I have this:

[info] Loading project definition from C:\Program Files (x86)\sbt\bin\project
[warn] Multiple resolvers having different access mechanism configured with same
 name 'sbt-plugin-releases'. To avoid conflict, Remove duplicate project resolve
rs (`resolvers`) or rename publishing resolver (`publishTo`).
[info] Set current project to GeoTrellis Tutorial Project (in build file:/C:/Pro
gram%20Files%20(x86)/sbt/bin/)

> run
> [info] Running chatta.Main
> CACHING TILE RESULT FOR RASTER FarmlandWithoutPrimeAgriculturalSoils
> CACHING TILE RESULT FOR RASTER PublicallyOwnedWorkingLands
> CACHING TILE RESULT FOR RASTER Wetlands
> CACHING TILE RESULT FOR RASTER PrivatelyOwnedWorkingLandsWithEasements
> CACHING TILE RESULT FOR RASTER ForestedLands
> CACHING TILE RESULT FOR RASTER ImperviousSurfaces_Barren Lands_Open Water
> CACHING TILE RESULT FOR RASTER PrimeAgriculturalSoilsNotForestedOrFarmland
> CACHING TILE RESULT FOR RASTER DevelopedLand
> CACHING TILE RESULT FOR RASTER Non-workingProtectedOrPublicLands
> CACHING TILE RESULT FOR RASTER FarmlandOrForestedLandsWithPrimeAgriculturalSoils

[INFO] [04/17/2015 17:54:11.726] [GeoTrellis-akka.actor.default-dispatcher-4] [a
kka://GeoTrellis/user/IO-HTTP/listener-0] Bound to localhost/127.0.0.1:8777

And now I want to see some map or something like that ... In README is written I should type http://localhost:8777/ and I will see a map but I have only this: 

The requested resource could not be found.

Please, I just don´t know HOW or WHAT TO DO ... This demo is just for local so I assumed it should work right?

Thanks and sorry, I guess main problem is between keybord and chair (me) but I am not programator ...

T

**Comment by mfsny** [comment]
Well, it does work for me, so the problem must really on your side. Where do you run sbt and where do you run your webbrowser? Because these must be on the same machine, i.e your PC or VM or whatever. It will NOT work if you are running sbt on some server and type http://localhost:8777 on your PC!
If you must run this on two different computers, for instance, because you have a Windows PC and sbt runs on Unix/Linux only, then you can change application.conf under src/main/resources. That's where "localhost" comes from 
````
geotrellis.hostname = "localhost" 
````
the last line of the file. You set it to the hostname of the computer, where sbt is running and can use Firefox on your local PC with address:
 ```` url
http://your.hostname:8777
````
or simply extend ./sbt run by the parameter using -D syntax, e.g. 
```` command
./sbt run -Dgeotrellis.hostname=your.hostname
````

**Comment by tikos** [comment]
Hi @slavo

Hm ... I was using manuals and I run the first one (
http://geotrellis.io/tutorials/webservice/spray/ ) and it worked ... But I
had many issues with dependencies etc ... In that firs sample SOLVED ...
Chatta sample is just not working ... And ... I am running SBT and my
webbrowser on same machines (no VM, just my PC).

SBT and Scala could run on Windows ... I have downloaded Windows version
from their webpages ...

Sorry but I don´t understand what are you trying to say me ... :(

2015-05-05 10:13 GMT+02:00 slavo <notifications@github.com>:

> Well, it does work for me, so the problem must really on your side. Where
> do you run sbt and where do you run your webbrowser? Because these must be
> on the same machine, i.e your PC or VM or whatever. It will NOT work if you
> are running sbt on some server and type http://localhost:8777 on your PC!
> If you must run this on two different computers, for instance, because you
> have a Windows PC and sbt runs on Unix/Linux only, then you can change
> application.conf under src/main/resources. That's where "localhost" comes
> from
>
> geotrellis.hostname = "localhost"
>
> the last line of the file. You set it to the hostname of the computer,
> where sbt is running and can use Firefox on your local PC with address:
>
> http://your.hostname:8777
>
> or simply extend ./sbt run by the parameter using -D syntax, e.g.
>
> ./sbt run -Dgeotrellis.hostname=your.hostname
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geotrellis/geotrellis-chatta-demo/issues/4#issuecomment-98989609>
> .
>



-- 
bc. Tomáš DROTTNER

*Katedra geoinformatiky * | *Department of Geoinformatics*
Univerzita Palackého v Olomouci  |  Palacký University in Olomouc
17. listopadu 50 | Olomouc, 771 46 | Czech Republic

**Comment by mfsny** [comment]
OK, so I'll try once again. It looks like your problem is *NOT* the fact, that you run SBT and webbrowser on two different hosts, which was my assumptions based on your description of the situation. How did you run SBT? I used ./sbt from the geotrellis folder and it did work without any problems, no dependency issues. If you get any troubles here: are you behind a proxy server? As far as I know, the geotrellis SBT script runs on Unix/Linux only, not under Windows (git bash), maybe this is the place you should doublecheck.

**Comment by tikos** [comment]
@mfsny

**Comment by mfsny** [comment]
I did not want to give you an impression that Geotrellis is NOT for Windows, I just wanted to say that BUILDING it on Windows does not seem to be possible.

Well, I did not follow the tutorial, I simply did "git clone https://...." and then changed directory to geotrellis and ran "./sbt run". And it worked!

**Comment by tikos** [comment]
I see ... Okay, its for Windows but it needs Linux also :P

Please, could you write exactly what did you use to run it? The rest of
"git clone ...." and how to change that ... I just wanted to be 100% sure
.. Because when I used that manual, steop by steop, it didn´t work and I am
not that skilled in it.

2015-05-05 17:13 GMT+02:00 slavo <notifications@github.com>:

> I did not want to give you an impression that Geotrellis is NOT for
> Windows, I just wanted to say that BUILDING it on Windows does not seem to
> be possible.
>
> Well, I did not follow the tutorial, I simply did "git clone https://...."
> and then changed directory to geotrellis and ran "./sbt run". And it worked!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geotrellis/geotrellis-chatta-demo/issues/4#issuecomment-99111498>
> .
>



-- 
bc. Tomáš DROTTNER

*Katedra geoinformatiky * | *Department of Geoinformatics*
Univerzita Palackého v Olomouci  |  Palacký University in Olomouc
17. listopadu 50 | Olomouc, 771 46 | Czech Republic

**Comment by mfsny** [comment]
Hi Tomas,
it runs on Java (JVM), ie. under Windows too, I think. It is jst much easier to build it using Linux, because the "sbt" command makes everything for you.

The "git clone" is using the HTTPS clone URL from the github homepage of the project
````
$ git clone https://github.com/geotrellis/geotrellis-chatta-demo.git
````
it creates the structure with two subfolders: static and geotrellis, so change to directory "geotrellis" run run "sbt"
````
$ cd geotrellis
$ ./sbt run
````
when done, and you get "... [GeoTrellis-akka.actor.default-dispatcher-4] [akka://GeoTrellis/user/IO-HTTP/listener-0] Bound to localhost/127.0.0.1:8777"
you can start your webbrowser and type URL:
 ````
http://localhost:8777
````

If these instructions do not help, then I am afraid it is much easier to ask some colleague of yours who knows Java/Scala for help.

Maj sa ;)
Slavo
PS. jak tipujes hokej?

**Comment by mfsny** [comment]
I used both a Linux image (Cloudera Quickstart VM CDH5.3, just because I use it for spark as well, it is based on CentOS) and a Linux server (RHEL6) and it worked on both.
I tried Git bash first, but had no luck, the sbt script from geotrellis folder did not run.
Best regards,
Slavo
PS. I also see it like USA-CAN in the final with Canada winning it. But you never know, the ice-hockey World Championship really starts at the quarterfinals.
PPS. I noticed your signature in one of the emails. University of Olomouc.

**Comment by pomadchin** [comment]
A very old conversation with old links. Can be closed and reopened / opened a new one if there is still an issue. Current GeoTrellis Chatta demo uses GeoTrellis `1.1.0` and uses `CollectionsApi` on server side. Spark is required for ingest.
